sudo: false
language: node_js
node_js:
  - '0.10'
  - '0.12'
  - 'iojs'
  - '4.0'
before_install:
  - npm install -g codeclimate-test-reporter grunt-cli
after_success:
  - codeclimate-test-reporter < ./coverage/lcov.info
  - gulp deployDoc
